apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - repos/repos-overrides.yaml
configMapGenerator:
  - name: deploy-parameters
    envs:
      - params
    options:
      disableNameSuffixHash: true
    namespace: flux-system
