apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: repos
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  interval: 60m
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./repos
  prune: true
  validation: client
